"""
LLM as the Brain: Creative Planning System
=========================================

This module implements the LLM-based creative planning system that focuses on:
- Natural language understanding
- Creative problem solving
- High-level plan generation
- Constraint interpretation

The LLM system does NOT do mathematical verification - that's handled by
the separate Mathematical Verifier system.
"""

import json
import re
from typing import Dict, List, Tuple, Any, Optional
from dataclasses import dataclass
from env.state import State
from env.backend import Environment


@dataclass
class NaturalLanguageGoal:
    """Represents a natural language goal from user."""
    description: str
    context: str
    constraints: List[str]
    priority: str  # "high", "medium", "low"


@dataclass
class HighLevelPlan:
    """Represents a high-level plan generated by LLM."""
    goal: str
    reasoning: str
    steps: List[str]
    assumptions: List[str]
    creativity_score: float
    feasibility_estimate: str  # "high", "medium", "low"


class LLMBrain:
    """
    LLM as the Brain: Creative planning and reasoning system.
    
    This system focuses on:
    - Understanding natural language goals
    - Generating creative solutions
    - Reasoning about constraints
    - Providing high-level plans
    
    It does NOT handle:
    - Mathematical verification (handled by verifier)
    - Safety guarantees (handled by verifier)
    - Low-level execution (handled by execution system)
    """
    
    def __init__(self, environment: Environment):
        """Initialize LLM brain system."""
        self.env = environment
        self.creativity_level = "high"  # "low", "medium", "high"
        self.constraint_parser = ConstraintParser()
        self.plan_generator = PlanGenerator()
    
    def understand_goal(self, natural_language_goal: str, context: str = "") -> NaturalLanguageGoal:
        """
        Parse and understand a natural language goal.
        
        Args:
            natural_language_goal: User's goal in natural language
            context: Additional context about the situation
            
        Returns:
            Structured goal representation
        """
        # Extract constraints from natural language
        constraints = self.constraint_parser.extract_constraints(natural_language_goal)
        
        # Determine priority based on language
        priority = self._extract_priority(natural_language_goal)
        
        return NaturalLanguageGoal(
            description=natural_language_goal,
            context=context,
            constraints=constraints,
            priority=priority
        )
    
    def generate_creative_plan(self, goal: NaturalLanguageGoal, 
                             current_state: State) -> HighLevelPlan:
        """
        Generate a creative high-level plan using LLM reasoning.
        
        Args:
            goal: Natural language goal
            current_state: Current world state
            
        Returns:
            Creative high-level plan
        """
        # Analyze the situation
        situation_analysis = self._analyze_situation(current_state, goal)
        
        # Generate creative solutions
        creative_solutions = self.plan_generator.generate_solutions(
            goal, current_state, situation_analysis
        )
        
        # Select best creative solution
        best_solution = self._select_best_solution(creative_solutions, goal)
        
        # Generate reasoning
        reasoning = self._generate_reasoning(best_solution, goal, current_state)
        
        # Estimate feasibility (without verification)
        feasibility = self._estimate_feasibility(best_solution, current_state)
        
        return HighLevelPlan(
            goal=goal.description,
            reasoning=reasoning,
            steps=best_solution["steps"],
            assumptions=best_solution["assumptions"],
            creativity_score=best_solution["creativity_score"],
            feasibility_estimate=feasibility
        )
    
    def refine_plan(self, plan: HighLevelPlan, feedback: str) -> HighLevelPlan:
        """
        Refine a plan based on feedback (e.g., from verifier).
        
        Args:
            plan: Current plan
            feedback: Feedback from verifier or user
            
        Returns:
            Refined plan
        """
        # Parse feedback
        issues = self._parse_feedback(feedback)
        
        # Generate alternative approaches
        alternatives = self.plan_generator.generate_alternatives(
            plan, issues, self.env
        )
        
        # Select best alternative
        best_alternative = self._select_best_alternative(alternatives, plan)
        
        return best_alternative
    
    def _extract_priority(self, goal_text: str) -> str:
        """Extract priority from natural language."""
        urgent_words = ["urgent", "emergency", "critical", "immediately", "asap"]
        if any(word in goal_text.lower() for word in urgent_words):
            return "high"
        
        important_words = ["important", "need", "should", "must"]
        if any(word in goal_text.lower() for word in important_words):
            return "medium"
        
        return "low"
    
    def _analyze_situation(self, state: State, goal: NaturalLanguageGoal) -> Dict[str, Any]:
        """Analyze current situation for planning."""
        analysis = {
            "available_objects": list(state.objects.keys()),
            "robot_position": state.robot,
            "gripper_content": state.gripper,
            "constraints": goal.constraints,
            "context": goal.context
        }
        
        # Add creative insights
        analysis["creative_opportunities"] = self._find_creative_opportunities(state)
        analysis["potential_challenges"] = self._identify_challenges(state, goal)
        
        return analysis
    
    def _find_creative_opportunities(self, state: State) -> List[str]:
        """Find creative opportunities in current state."""
        opportunities = []
        
        # Look for interesting object combinations
        objects = list(state.objects.keys())
        if len(objects) >= 2:
            opportunities.append(f"Could combine {objects[0]} and {objects[1]} creatively")
        
        # Look for spatial opportunities
        if state.robot != (0, 0):
            opportunities.append("Robot is positioned for interesting maneuvers")
        
        return opportunities
    
    def _identify_challenges(self, state: State, goal: NaturalLanguageGoal) -> List[str]:
        """Identify potential challenges."""
        challenges = []
        
        # Check constraint complexity
        if len(goal.constraints) > 3:
            challenges.append("Many constraints to satisfy simultaneously")
        
        # Check object availability
        if "pick" in goal.description.lower() and not state.objects:
            challenges.append("No objects available for manipulation")
        
        return challenges
    
    def _select_best_solution(self, solutions: List[Dict], goal: NaturalLanguageGoal) -> Dict:
        """Select the best creative solution."""
        # Score solutions based on creativity and goal alignment
        scored_solutions = []
        for solution in solutions:
            score = self._score_solution(solution, goal)
            scored_solutions.append((score, solution))
        
        # Return highest scoring solution
        scored_solutions.sort(key=lambda x: x[0], reverse=True)
        return scored_solutions[0][1]
    
    def _score_solution(self, solution: Dict, goal: NaturalLanguageGoal) -> float:
        """Score a solution based on creativity and goal alignment."""
        creativity_score = solution.get("creativity_score", 0.5)
        goal_alignment = self._calculate_goal_alignment(solution, goal)
        constraint_satisfaction = self._calculate_constraint_satisfaction(solution, goal)
        
        return (creativity_score * 0.4 + 
                goal_alignment * 0.4 + 
                constraint_satisfaction * 0.2)
    
    def _calculate_goal_alignment(self, solution: Dict, goal: NaturalLanguageGoal) -> float:
        """Calculate how well solution aligns with goal."""
        # Simple keyword matching for now
        goal_words = set(goal.description.lower().split())
        solution_words = set(" ".join(solution["steps"]).lower().split())
        
        overlap = len(goal_words.intersection(solution_words))
        return min(overlap / len(goal_words), 1.0)
    
    def _calculate_constraint_satisfaction(self, solution: Dict, goal: NaturalLanguageGoal) -> float:
        """Calculate how well solution satisfies constraints."""
        if not goal.constraints:
            return 1.0
        
        satisfied = 0
        for constraint in goal.constraints:
            if self._solution_satisfies_constraint(solution, constraint):
                satisfied += 1
        
        return satisfied / len(goal.constraints)
    
    def _solution_satisfies_constraint(self, solution: Dict, constraint: str) -> bool:
        """Check if solution satisfies a constraint."""
        # Simple keyword-based checking
        constraint_lower = constraint.lower()
        solution_text = " ".join(solution["steps"]).lower()
        
        # Check for constraint violations
        if "never" in constraint_lower and "mix" in constraint_lower:
            # Check if solution involves mixing
            if "mix" in solution_text:
                return False
        
        if "don't" in constraint_lower and "heat" in constraint_lower:
            # Check if solution involves heating
            if "heat" in solution_text:
                return False
        
        return True
    
    def _generate_reasoning(self, solution: Dict, goal: NaturalLanguageGoal, 
                          state: State) -> str:
        """Generate reasoning for the solution."""
        reasoning_parts = []
        
        reasoning_parts.append(f"Goal: {goal.description}")
        reasoning_parts.append(f"Context: {goal.context}")
        reasoning_parts.append(f"Constraints: {', '.join(goal.constraints)}")
        reasoning_parts.append(f"Solution: {' -> '.join(solution['steps'])}")
        reasoning_parts.append(f"Creativity: {solution['creativity_score']:.2f}")
        
        return "\n".join(reasoning_parts)
    
    def _estimate_feasibility(self, solution: Dict, state: State) -> str:
        """Estimate feasibility without mathematical verification."""
        # Simple heuristic-based estimation
        step_count = len(solution["steps"])
        
        if step_count <= 3:
            return "high"
        elif step_count <= 6:
            return "medium"
        else:
            return "low"
    
    def _parse_feedback(self, feedback: str) -> List[str]:
        """Parse feedback into specific issues."""
        issues = []
        
        if "unsafe" in feedback.lower():
            issues.append("safety_violation")
        if "impossible" in feedback.lower():
            issues.append("impossible_action")
        if "constraint" in feedback.lower():
            issues.append("constraint_violation")
        
        return issues
    
    def _select_best_alternative(self, alternatives: List[Dict], 
                               original_plan: HighLevelPlan) -> HighLevelPlan:
        """Select best alternative plan."""
        if not alternatives:
            return original_plan
        
        # Score alternatives
        scored_alternatives = []
        for alt in alternatives:
            score = self._score_alternative(alt, original_plan)
            scored_alternatives.append((score, alt))
        
        scored_alternatives.sort(key=lambda x: x[0], reverse=True)
        best_alt = scored_alternatives[0][1]
        
        return HighLevelPlan(
            goal=original_plan.goal,
            reasoning=f"Refined plan based on feedback: {best_alt['reasoning']}",
            steps=best_alt["steps"],
            assumptions=best_alt["assumptions"],
            creativity_score=best_alt["creativity_score"],
            feasibility_estimate=best_alt["feasibility_estimate"]
        )
    
    def _score_alternative(self, alternative: Dict, original: HighLevelPlan) -> float:
        """Score an alternative plan."""
        creativity_score = alternative.get("creativity_score", 0.5)
        feasibility_score = 0.8 if alternative.get("feasibility_estimate") == "high" else 0.5
        
        return creativity_score * 0.6 + feasibility_score * 0.4


class ConstraintParser:
    """Parses natural language constraints into structured rules."""
    
    def extract_constraints(self, text: str) -> List[str]:
        """Extract constraints from natural language text."""
        constraints = []
        
        # Look for constraint patterns
        constraint_patterns = [
            r"never\s+([^.!?]+)",
            r"don'?t\s+([^.!?]+)",
            r"avoid\s+([^.!?]+)",
            r"must\s+not\s+([^.!?]+)",
            r"should\s+not\s+([^.!?]+)"
        ]
        
        for pattern in constraint_patterns:
            matches = re.findall(pattern, text, re.IGNORECASE)
            constraints.extend(matches)
        
        return constraints


class PlanGenerator:
    """Generates creative high-level plans."""
    
    def generate_solutions(self, goal: NaturalLanguageGoal, state: State, 
                         analysis: Dict[str, Any]) -> List[Dict]:
        """Generate multiple creative solutions."""
        solutions = []
        
        # Generate different creative approaches
        solutions.append(self._generate_direct_approach(goal, state, analysis))
        solutions.append(self._generate_creative_approach(goal, state, analysis))
        solutions.append(self._generate_constraint_aware_approach(goal, state, analysis))
        
        return solutions
    
    def _generate_direct_approach(self, goal: NaturalLanguageGoal, state: State, 
                                analysis: Dict[str, Any]) -> Dict:
        """Generate direct, straightforward approach."""
        steps = [
            "Analyze current situation",
            "Identify key objects needed",
            "Plan direct path to goal",
            "Execute plan step by step"
        ]
        
        return {
            "steps": steps,
            "assumptions": ["Objects are available", "Direct path exists"],
            "creativity_score": 0.3,
            "reasoning": "Direct approach focusing on efficiency"
        }
    
    def _generate_creative_approach(self, goal: NaturalLanguageGoal, state: State, 
                                  analysis: Dict[str, Any]) -> Dict:
        """Generate creative, novel approach."""
        steps = [
            "Think outside the box",
            "Consider unconventional methods",
            "Leverage available resources creatively",
            "Implement innovative solution"
        ]
        
        return {
            "steps": steps,
            "assumptions": ["Creative solutions are possible", "Resources can be repurposed"],
            "creativity_score": 0.9,
            "reasoning": "Creative approach using novel methods"
        }
    
    def _generate_constraint_aware_approach(self, goal: NaturalLanguageGoal, state: State, 
                                          analysis: Dict[str, Any]) -> Dict:
        """Generate approach that carefully considers constraints."""
        steps = [
            "Carefully analyze all constraints",
            "Plan around limitations",
            "Ensure constraint compliance",
            "Execute with safety in mind"
        ]
        
        return {
            "steps": steps,
            "assumptions": ["All constraints must be satisfied", "Safety is paramount"],
            "creativity_score": 0.6,
            "reasoning": "Constraint-aware approach prioritizing safety"
        }
    
    def generate_alternatives(self, plan: HighLevelPlan, issues: List[str], 
                            env: Environment) -> List[Dict]:
        """Generate alternative plans based on feedback."""
        alternatives = []
        
        if "safety_violation" in issues:
            alternatives.append(self._generate_safer_alternative(plan))
        
        if "impossible_action" in issues:
            alternatives.append(self._generate_feasible_alternative(plan))
        
        if "constraint_violation" in issues:
            alternatives.append(self._generate_constraint_compliant_alternative(plan))
        
        return alternatives
    
    def _generate_safer_alternative(self, plan: HighLevelPlan) -> Dict:
        """Generate safer alternative."""
        return {
            "steps": ["Use safer methods", "Avoid risky actions", "Prioritize safety"],
            "assumptions": ["Safety is top priority"],
            "creativity_score": 0.4,
            "reasoning": "Safer alternative to address safety concerns",
            "feasibility_estimate": "high"
        }
    
    def _generate_feasible_alternative(self, plan: HighLevelPlan) -> Dict:
        """Generate more feasible alternative."""
        return {
            "steps": ["Use simpler methods", "Break into smaller steps", "Ensure feasibility"],
            "assumptions": ["Simpler is better", "Step-by-step approach"],
            "creativity_score": 0.5,
            "reasoning": "More feasible alternative",
            "feasibility_estimate": "high"
        }
    
    def _generate_constraint_compliant_alternative(self, plan: HighLevelPlan) -> Dict:
        """Generate constraint-compliant alternative."""
        return {
            "steps": ["Review all constraints", "Plan within limits", "Ensure compliance"],
            "assumptions": ["All constraints must be followed"],
            "creativity_score": 0.6,
            "reasoning": "Constraint-compliant alternative",
            "feasibility_estimate": "medium"
        }
